// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CacheCreationDetail 细分缓存创建 tokens。
 */
export class CacheCreationDetail {
    "Ephemeral5mTokens": number;
    "Ephemeral1hTokens": number;

    /** Creates a new CacheCreationDetail instance. */
    constructor($$source: Partial<CacheCreationDetail> = {}) {
        if (!("Ephemeral5mTokens" in $$source)) {
            this["Ephemeral5mTokens"] = 0;
        }
        if (!("Ephemeral1hTokens" in $$source)) {
            this["Ephemeral1hTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheCreationDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): CacheCreationDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CacheCreationDetail($$parsedSource as Partial<CacheCreationDetail>);
    }
}

/**
 * ServiceTier 描述 OpenAI/Azure 等上游请求时选的服务档位,影响单价。
 */
export enum ServiceTier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ServiceTierDefault 标准档位(空值/不指定时的默认行为)。
     */
    ServiceTierDefault = "",

    /**
     * ServiceTierObservedDefault 上游明确回传 "default" 字面量,与 ServiceTierDefault 区分观测态。
     */
    ServiceTierObservedDefault = "default",

    /**
     * ServiceTierStandard 部分平台用 "standard" 表示默认档,计费与 default 一致。
     */
    ServiceTierStandard = "standard",

    /**
     * ServiceTierPriority 优先档位,上游单价更高但延迟更低。
     */
    ServiceTierPriority = "priority",

    /**
     * ServiceTierFlex 低价异步档位,通常与批处理同价。
     */
    ServiceTierFlex = "flex",
};

/**
 * UsageSnapshot 描述一次请求的 token 用量。
 */
export class UsageSnapshot {
    "InputTokens": number;
    "OutputTokens": number;
    "ReasoningTokens": number;
    "CacheCreateTokens": number;
    "CacheReadTokens": number;
    "CacheCreation": CacheCreationDetail | null;

    /**
     * ServiceTier 当前请求实际走的服务档位;空值视为 default,不影响定价。
     */
    "ServiceTier": ServiceTier;

    /** Creates a new UsageSnapshot instance. */
    constructor($$source: Partial<UsageSnapshot> = {}) {
        if (!("InputTokens" in $$source)) {
            this["InputTokens"] = 0;
        }
        if (!("OutputTokens" in $$source)) {
            this["OutputTokens"] = 0;
        }
        if (!("ReasoningTokens" in $$source)) {
            this["ReasoningTokens"] = 0;
        }
        if (!("CacheCreateTokens" in $$source)) {
            this["CacheCreateTokens"] = 0;
        }
        if (!("CacheReadTokens" in $$source)) {
            this["CacheReadTokens"] = 0;
        }
        if (!("CacheCreation" in $$source)) {
            this["CacheCreation"] = null;
        }
        if (!("ServiceTier" in $$source)) {
            this["ServiceTier"] = ServiceTier.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageSnapshot {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CacheCreation" in $$parsedSource) {
            $$parsedSource["CacheCreation"] = $$createField5_0($$parsedSource["CacheCreation"]);
        }
        return new UsageSnapshot($$parsedSource as Partial<UsageSnapshot>);
    }
}

// Private type creation functions
const $$createType0 = CacheCreationDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
