// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CustomCliService 自定义 CLI 工具服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTool 创建新工具
 */
export function CreateTool(tool: $models.CustomCliTool): $CancellablePromise<$models.CustomCliTool | null> {
    return $Call.ByID(677445981, tool).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteTool 删除工具
 */
export function DeleteTool(id: string): $CancellablePromise<void> {
    return $Call.ByID(622923482, id);
}

/**
 * DisableProxy 禁用代理
 */
export function DisableProxy(toolId: string): $CancellablePromise<void> {
    return $Call.ByID(1117651131, toolId);
}

/**
 * EnableProxy 启用代理
 */
export function EnableProxy(toolId: string): $CancellablePromise<void> {
    return $Call.ByID(1441904828, toolId);
}

/**
 * GetConfigContent 获取配置文件内容
 */
export function GetConfigContent(toolId: string, fileId: string): $CancellablePromise<string> {
    return $Call.ByID(3718007080, toolId, fileId);
}

/**
 * GetLockedFields 获取锁定字段列表
 */
export function GetLockedFields(toolId: string): $CancellablePromise<string[]> {
    return $Call.ByID(2663671858, toolId).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetTool 获取单个工具
 */
export function GetTool(id: string): $CancellablePromise<$models.CustomCliTool | null> {
    return $Call.ByID(2712692095, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListTools 获取所有自定义 CLI 工具
 */
export function ListTools(): $CancellablePromise<$models.CustomCliTool[]> {
    return $Call.ByID(679310818).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ProxyStatus 获取代理状态
 */
export function ProxyStatus(toolId: string): $CancellablePromise<$models.CustomCliProxyStatus | null> {
    return $Call.ByID(3969379143, toolId).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SaveConfigContent 保存配置文件内容
 */
export function SaveConfigContent(toolId: string, fileId: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3436188653, toolId, fileId, content);
}

/**
 * UpdateTool 更新工具
 */
export function UpdateTool(id: string, tool: $models.CustomCliTool): $CancellablePromise<void> {
    return $Call.ByID(1680725388, id, tool);
}

// Private type creation functions
const $$createType0 = $models.CustomCliTool.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = $models.CustomCliProxyStatus.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
