// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeepLinkService 深度链接服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ImportProviderFromDeepLink 从深度链接导入供应商
 */
export function ImportProviderFromDeepLink(request: $models.DeepLinkImportRequest | null): $CancellablePromise<string> {
    return $Call.ByID(2087032230, request);
}

/**
 * ParseDeepLinkURL 解析 ccswitch:// URL
 * 预期格式: ccswitch://v1/import?resource=provider&app=claude&name=...&homepage=...&endpoint=...&apiKey=...
 */
export function ParseDeepLinkURL(urlStr: string): $CancellablePromise<$models.DeepLinkImportRequest | null> {
    return $Call.ByID(3816480018, urlStr).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Start Wails生命周期方法
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3178862184);
}

/**
 * Stop Wails生命周期方法
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(839496268);
}

// Private type creation functions
const $$createType0 = $models.DeepLinkImportRequest.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
