// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvCheckService 环境变量检测服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckEnvConflicts 检查指定平台的环境变量冲突
 */
export function CheckEnvConflicts(app: string): $CancellablePromise<$models.EnvConflict[]> {
    return $Call.ByID(1941592683, app).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Start Wails生命周期方法
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1143131277);
}

/**
 * Stop Wails生命周期方法
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1280229439);
}

// Private type creation functions
const $$createType0 = $models.EnvConflict.createFrom;
const $$createType1 = $Create.Array($$createType0);
