// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetStatus(): $CancellablePromise<$models.ConfigImportStatus> {
    return $Call.ByID(2109164227).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportAll 从默认路径导入 cc-switch 配置
 */
export function ImportAll(): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(124174517).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportFromPath 从指定路径导入 cc-switch 配置
 */
export function ImportFromPath(path: string): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(2519238097, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsFirstRun 检查是否首次使用（用于显示导入提示）
 */
export function IsFirstRun(): $CancellablePromise<boolean> {
    return $Call.ByID(4249749624);
}

/**
 * MarkFirstRunDone 标记首次使用已完成（不再显示导入提示）
 */
export function MarkFirstRunDone(): $CancellablePromise<void> {
    return $Call.ByID(838327945);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3119656637);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2083779375);
}

// Private type creation functions
const $$createType0 = $models.ConfigImportStatus.createFrom;
const $$createType1 = $models.ConfigImportResult.createFrom;
