// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteProject(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(1017476374, projectPath);
}

export function DeleteSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2666625055, sessionID);
}

export function GetSessionConversationDetail(sessionID: string): $CancellablePromise<$models.SessionConversationDetail> {
    return $Call.ByID(2599842864, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetSnapshot(): $CancellablePromise<$models.ProjectManagerSnapshot> {
    return $Call.ByID(1402859362).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListProjectSessions(projectPath: string): $CancellablePromise<$models.SessionSummary[]> {
    return $Call.ByID(3482480734, projectPath).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListProjects(): $CancellablePromise<$models.ProjectSummary[]> {
    return $Call.ByID(2806071092).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListRecentSessions(): $CancellablePromise<$models.SessionSummary[]> {
    return $Call.ByID(1055571516).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenProjectFolder(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(962621967, projectPath);
}

export function OpenProjectTerminal(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(3615257703, projectPath);
}

export function OpenSessionTerminal(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1009513054, sessionID);
}

export function OpenSessionTerminalWithSession(session: $models.SessionSummary): $CancellablePromise<void> {
    return $Call.ByID(2081160126, session);
}

export function PruneSessionConversation(sessionID: string, messageIDs: string[]): $CancellablePromise<$models.SessionConversationDetail> {
    return $Call.ByID(1933876465, sessionID, messageIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RefreshProjectIndex(): $CancellablePromise<$models.ProjectManagerSnapshot> {
    return $Call.ByID(4024905526).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RenameProject(projectPath: string, displayName: string): $CancellablePromise<void> {
    return $Call.ByID(690378353, projectPath, displayName);
}

export function RenameSession(sessionID: string, displayName: string): $CancellablePromise<void> {
    return $Call.ByID(1130005944, sessionID, displayName);
}

export function RunProjectAICommit(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(1250976875, projectPath);
}

// Private type creation functions
const $$createType0 = $models.SessionConversationDetail.createFrom;
const $$createType1 = $models.ProjectManagerSnapshot.createFrom;
const $$createType2 = $models.SessionSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ProjectSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
