// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SpeedTestService 测速服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Start Wails生命周期方法
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(336583549);
}

/**
 * Stop Wails生命周期方法
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(4077816815);
}

/**
 * TestEndpoints 测试一组端点的响应延迟
 * 使用并发请求，每个端点先进行一次热身请求，再测量第二次请求的延迟
 */
export function TestEndpoints(urls: string[], timeoutSecs: number | null): $CancellablePromise<$models.EndpointLatency[]> {
    return $Call.ByID(846920271, urls, timeoutSecs).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.EndpointLatency.createFrom;
const $$createType1 = $Create.Array($$createType0);
