// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService 自动更新服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelDownload 取消下载
 */
export function CancelDownload(): $CancellablePromise<void> {
    return $Call.ByID(960389845);
}

/**
 * CheckUpdate 检查更新
 * 返回更新信息，如果无更新则返回 nil
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3762820960).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DismissUpdate 忽略指定版本
 */
export function DismissUpdate(version: string): $CancellablePromise<void> {
    return $Call.ByID(2790445404, version);
}

/**
 * DownloadUpdate 下载更新
 */
export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(306369946);
}

/**
 * GetDismissedVersion 获取被忽略的版本
 */
export function GetDismissedVersion(): $CancellablePromise<string> {
    return $Call.ByID(2398744002);
}

/**
 * GetState 获取当前状态快照
 */
export function GetState(): $CancellablePromise<$models.UpdateStateSnapshot | null> {
    return $Call.ByID(2036411274).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RequestRestart 请求重启并更新
 */
export function RequestRestart(): $CancellablePromise<void> {
    return $Call.ByID(1101698587);
}

/**
 * SetApp 设置 Wails App 引用
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2055329212, app);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.UpdateStateSnapshot.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
