// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

export function OpenSecondWindow(): $CancellablePromise<void> {
    return $Call.ByID(1306260514);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3487267257, app);
}

export function SetTrayWindowHeight(height: number): $CancellablePromise<void> {
    return $Call.ByID(3935785145, height);
}

/**
 * ShowMainWindow 供独立桌宠窗唤起主窗口；设置和 Studio 属于主应用页面，
 * 不能在透明桌宠窗里再挂一套路由，否则会重新引入主布局和焦点冲突。
 */
export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3326919698);
}
