// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplySingleProvider 直连应用单一供应商（仅在代理关闭时可用）
 * 将指定 provider 的配置直接写入 Codex 的 config.toml 和 auth.json
 */
export function ApplySingleProvider(providerID: number): $CancellablePromise<void> {
    return $Call.ByID(2208729147, providerID);
}

export function DisableProxy(): $CancellablePromise<void> {
    return $Call.ByID(3815925570);
}

export function EnableProxy(): $CancellablePromise<void> {
    return $Call.ByID(922948163);
}

/**
 * GetDirectAppliedProviderID 返回当前直连应用的 Provider ID
 * 通过读取 CLI 配置文件反推当前使用的 provider
 */
export function GetDirectAppliedProviderID(): $CancellablePromise<number | null> {
    return $Call.ByID(853555268);
}

/**
 * GetModelInstructionsFile 返回当前 Codex config.toml 中配置的 model_instructions_file。
 * 若配置文件不存在或未配置该字段，则返回空字符串。
 */
export function GetModelInstructionsFile(): $CancellablePromise<string> {
    return $Call.ByID(3474225876);
}

export function ProxyStatus(): $CancellablePromise<$models.ClaudeProxyStatus> {
    return $Call.ByID(419975348).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetModelInstructionsFile 写入 Codex config.toml 的 model_instructions_file。
 * 空字符串表示删除该字段；相对路径会在保存前归一化为绝对路径。
 */
export function SetModelInstructionsFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(24852744, path);
}

// Private type creation functions
const $$createType0 = $models.ClaudeProxyStatus.createFrom;
