// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddRepo(repo: $models.skillRepoConfig): $CancellablePromise<$models.skillRepoConfig[]> {
    return $Call.ByID(2020364064, repo).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSkillContent 获取技能的 SKILL.md 内容
 */
export function GetSkillContent(directory: string, platform: string, location: string): $CancellablePromise<string> {
    return $Call.ByID(3743777913, directory, platform, location);
}

/**
 * InstallSkill installs a skill directory from the configured repositories.
 * 支持 platform 和 location 参数，用于指定安装的平台和位置
 */
export function InstallSkill(req: $models.installRequest): $CancellablePromise<void> {
    return $Call.ByID(2924128557, req);
}

export function ListRepos(): $CancellablePromise<$models.skillRepoConfig[]> {
    return $Call.ByID(1704737214).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListSkills aggregates skills from configured repositories and the local install directory.
 */
export function ListSkills(): $CancellablePromise<$models.Skill[]> {
    return $Call.ByID(3387382203).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListSkillsForPlatform 列出指定平台的技能（用户级 + 项目级）
 */
export function ListSkillsForPlatform(platform: string): $CancellablePromise<$models.Skill[]> {
    return $Call.ByID(2689607053, platform).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * OpenSkillFolder 打开技能目录
 */
export function OpenSkillFolder(platform: string, location: string): $CancellablePromise<void> {
    return $Call.ByID(216615946, platform, location);
}

export function RemoveRepo(owner: string, name: string): $CancellablePromise<$models.skillRepoConfig[]> {
    return $Call.ByID(2067147157, owner, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveSkillContent 保存技能的 SKILL.md 内容
 */
export function SaveSkillContent(directory: string, platform: string, location: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3441672290, directory, platform, location, content);
}

export function ToggleSkill(directory: string, platform: string, location: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2154856646, directory, platform, location, enabled);
}

export function ToggleSkillEnabled(directory: string, platform: string, location: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3133699123, directory, platform, location, enabled);
}

export function ToggleSkillInjection(directory: string, platform: string, location: string, injectEnabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4290718375, directory, platform, location, injectEnabled);
}

export function UninstallSkill(directory: string): $CancellablePromise<void> {
    return $Call.ByID(3488362258, directory);
}

/**
 * UninstallSkillEx 卸载技能（支持多平台多位置）
 */
export function UninstallSkillEx(directory: string, platform: string, location: string): $CancellablePromise<void> {
    return $Call.ByID(3072081143, directory, platform, location);
}

// Private type creation functions
const $$createType0 = $models.skillRepoConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Skill.createFrom;
const $$createType3 = $Create.Array($$createType2);
