// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAppSettings returns the persisted app settings or defaults if the file does not exist.
 */
export function GetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(55540836).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSpeechProviderSelection 返回应用级语音识别选择；未配置时返回空引用，
 * 调用方必须把它当成“不可用”处理，禁止回退到聊天或 TTS provider。
 */
export function GetSpeechProviderSelection(): $CancellablePromise<$models.PetSpeechProviderSelection> {
    return $Call.ByID(610070333).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveAppSettings persists the provided settings to disk.
 */
export function SaveAppSettings(settings: $models.AppSettings): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(39874379, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveSpeechProviderSelection 只更新 speech 三元组，先读取完整设置再保存，
 * 避免设置页保存语音时覆盖预算、抓包等不相关配置。
 */
export function SaveSpeechProviderSelection(selection: $models.PetSpeechProviderSelection): $CancellablePromise<$models.PetSpeechProviderSelection> {
    return $Call.ByID(1277529250, selection).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
const $$createType1 = $models.PetSpeechProviderSelection.createFrom;
