// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetAIAPIService 是 Wails 与 PetAIService 之间的薄适配层。
 * bridge 只持有核心服务，不拥有 provider、网络请求或持久化职责，避免在 Wails
 * 方法中复制凭据处理、HTTP/SSE 解析和请求状态管理，保证这些规则只有一个 owner。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelChat 只转发 requestId，不在 bridge 中维护第二份活动请求表。
 */
export function CancelChat(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(1675653031, requestID);
}

export function CancelSpeech(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(4019004571, requestID);
}

/**
 * GenerateDreamText 转发同步梦境文本请求，网络和 provider 解析仍由核心服务负责。
 */
export function GenerateDreamText(request: $models.PetDreamTextRequest): $CancellablePromise<string> {
    return $Call.ByID(3675607476, request);
}

/**
 * StartChat 转发异步聊天请求；Wails 方法没有可注入的请求 context，取消由
 * CancelChat 根据 requestId 触发核心服务保存的取消函数。
 */
export function StartChat(request: $models.PetChatRequest): $CancellablePromise<$models.PetChatStartResult> {
    return $Call.ByID(2049468923, request).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StartSpeechStream 返回 requestId 后由 PetAudioEventEmitter 推送 chunk/completed 等事件；
 * bridge 不复制活动请求表，取消仍统一走核心服务的 context。
 */
export function StartSpeechStream(request: $models.PetSpeechRequest): $CancellablePromise<$models.PetSpeechStartResult> {
    return $Call.ByID(4050502423, request).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SynthesizeSpeech 转发同步语音请求，并把核心服务返回的音频三元组包装成稳定结果。
 */
export function SynthesizeSpeech(request: $models.PetSpeechRequest): $CancellablePromise<$models.PetSpeechResult> {
    return $Call.ByID(3945374169, request).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * TranscribeAudio 是桌宠录音输入的同步桥接；音频解码、multipart 边界和 provider
 * 认证仍由核心服务负责，Wails 层只暴露清洗后的文本结果。
 */
export function TranscribeAudio(request: $models.PetTranscriptionRequest): $CancellablePromise<$models.PetTranscriptionResult> {
    return $Call.ByID(4290032578, request).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PetChatStartResult.createFrom;
const $$createType1 = $models.PetSpeechStartResult.createFrom;
const $$createType2 = $models.PetSpeechResult.createFrom;
const $$createType3 = $models.PetTranscriptionResult.createFrom;
