// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetDreamAPIService 是 Wails 与 PetDreamService 之间的薄适配器。
 * 它只负责把 petId、归档目录和后端仓储组装起来，不重复梦境归一化规则。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyEmotion(petID: string, emotion: $models.PetDreamEmotion): $CancellablePromise<void> {
    return $Call.ByID(710466669, petID, emotion);
}

export function DeleteHistory(petID: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1938744849, petID, id);
}

export function ListHistory(petID: string, page: number, pageSize: number): $CancellablePromise<$models.PetDreamHistoryPage> {
    return $Call.ByID(1087367452, petID, page, pageSize).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ReadImage 返回受控 data URL，避免 renderer 通过 file:// 或绝对路径读取本地文件。
 */
export function ReadImage(petID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(4271197637, petID, name);
}

export function SaveHistory(petID: string, record: $models.PetDreamHistoryRecord): $CancellablePromise<void> {
    return $Call.ByID(562553827, petID, record);
}

/**
 * StoreImage 只接收生成器已经解码的图片字节，返回 basename；绝对路径永远不
 * 进入前端协议，避免把用户目录结构暴露给桌宠窗口。
 */
export function StoreImage(petID: string, mediaType: string, data: string): $CancellablePromise<string> {
    return $Call.ByID(2674119690, petID, mediaType, data);
}

// Private type creation functions
const $$createType0 = $models.PetDreamHistoryPage.createFrom;
