// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetImageAPIService 是 Wails 与 PetImageService 之间的薄 bridge。
 * provider reader、HTTP transport、凭据处理和图片校验全部由核心服务拥有，
 * bridge 不复制任何 provider 配置，也不把 context/HTTP 细节暴露给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GenerateImage 使用 Wails 可调用的无 context 签名；核心服务仍通过
 * context.Background() 和内部超时边界保证请求可收敛。参考图优先接受
 * referenceImage.data 中的已裁 idle 单帧 bare base64/data URL，也兼容受控的
 * idle 单帧本地路径；核心服务会解码、校验后决定 generations/edits 路径。
 * []byte 会由 Wails JSON 编码为 base64，前端拿到的是本地图片 bytes，而不是远程 URL。
 */
export function GenerateImage(request: $models.PetImageRequest): $CancellablePromise<$models.PetImageResult> {
    return $Call.ByID(1976622278, request).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PetImageResult.createFrom;
