// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetMediaAPIService 将已经存在的媒体纯函数暴露给 Wails。
 * 请求只接受 base64 图片数据，不接受任意 filePath；这样生成链路可以复用同一套
 * ChromaKey/Normalize/Atlas 规则，同时不把 Electron 文件 IPC 的越权边界带进目标应用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyChromaKey 将生成图片的指定色键背景转成透明像素。
 */
export function ApplyChromaKey(request: $models.PetChromaKeyRequest): $CancellablePromise<$models.PetChromaKeyResult> {
    return $Call.ByID(2808971948, request).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * NormalizeSprite 裁剪透明边缘并按统一主体高度生成 PNG，供 atlas 生成前复用。
 */
export function NormalizeSprite(request: $models.PetSpriteNormalizationAPIRequest): $CancellablePromise<$models.PetSpriteNormalizationAPIResult> {
    return $Call.ByID(2652916593, request).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PackAtlas 将每个 action 的 base64 帧按固定 action-row 布局打包。
 */
export function PackAtlas(request: $models.PetAtlasPackAPIRequest): $CancellablePromise<$models.PetAtlasPackAPIResult> {
    return $Call.ByID(923249419, request).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SplitActionSheet 只接受 PNG base64，且只在内存中处理。源项目的实现写临时文件是
 * Electron IPC 约束，在 Wails 目标栈里没有必要；返回裸 base64 还能让前端继续复用
 * NormalizeSprite 的单帧校验和透明背景处理。
 */
export function SplitActionSheet(request: $models.PetActionSheetSplitRequest): $CancellablePromise<$models.PetActionSheetSplitResult> {
    return $Call.ByID(1034489472, request).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PetChromaKeyResult.createFrom;
const $$createType1 = $models.PetSpriteNormalizationAPIResult.createFrom;
const $$createType2 = $models.PetAtlasPackAPIResult.createFrom;
const $$createType3 = $models.PetActionSheetSplitResult.createFrom;
