// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetMemoryService 管理可编辑的长期记忆。服务层负责去重、容量和指令解析，
 * DAO 只负责按宠物 ID 持久化记录，避免前端自行维护一份不一致的记忆列表。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Append 从模型隐藏指令或设置页导入事实。相同文本不会重复写入，超出上限时
 * 删除最旧记录，保证提示词大小可控，也避免数据库无限增长。
 */
export function Append(texts: string[]): $CancellablePromise<$models.PetMemoryRecord[]> {
    return $Call.ByID(1315322378, texts).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(3528408799);
}

export function List(): $CancellablePromise<$models.PetMemoryRecord[]> {
    return $Call.ByID(2132609978).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Remove(id: string): $CancellablePromise<void> {
    return $Call.ByID(1752406602, id);
}

// Private type creation functions
const $$createType0 = $models.PetMemoryRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
