// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetStudioAPIService 是 Wails 面向 Studio 的独立适配器。
 * 文件只是 atlas/manifest 载体，数据库记录仍然是皮肤的唯一事实来源。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSkin 只删除数据库确认存在的自定义皮肤，且目录必须精确位于受控 root/<skinId>。
 */
export function DeleteSkin(petID: string, skinID: string): $CancellablePromise<void> {
    return $Call.ByID(15123549, petID, skinID);
}

/**
 * GetRoot 只返回服务端计算出的受控资源 root，供设置页展示目录位置；
 * 前端不能传入任意路径，也不能通过皮肤记录反推出磁盘布局。
 */
export function GetRoot(): $CancellablePromise<string> {
    return $Call.ByID(852712849);
}

/**
 * ListSkins 返回数据库记录，但绝不把本地路径泄露给前端。
 */
export function ListSkins(petID: string): $CancellablePromise<$models.PetSkinRecord[]> {
    return $Call.ByID(3464716919, petID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenRoot 在打开前再次校验受控 root，并只把该 root 交给系统文件管理器。
 * root 不存在时创建它，保证用户点击“打开目录”不会得到无意义的空路径错误。
 */
export function OpenRoot(): $CancellablePromise<void> {
    return $Call.ByID(1446915791);
}

/**
 * ReadSkin 读取 Studio 可编辑的 atlas。空 skinID 固定读取默认内置皮肤，
 * 非空 skinID 只允许读取当前 petID 的记录，避免通过 skinId 枚举其他宠物的自定义资源。
 */
export function ReadSkin(petID: string, skinID: string): $CancellablePromise<$models.PetStudioReadSkinResult> {
    return $Call.ByID(2549824146, petID, skinID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveSkin 原子保存一个已经打包好的 atlas 和 manifest，并可选绑定为当前皮肤。
 * 请求没有 outputDir/filePath 字段，所有资源都只能落到 root/<skinId>。
 */
export function SaveSkin(petID: string, request: $models.PetStudioSaveSkinRequest): $CancellablePromise<$models.PetSkinRecord> {
    return $Call.ByID(1819632287, petID, request).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PetSkinRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PetStudioReadSkinResult.createFrom;
