// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetSchedulerAPI 只负责 Wails 输入输出和依赖编排：数据库归 JobStore/持久化 owner，
 * action 的属性规则归 PetService/调度器。这样 API 层不会出现第二套计划校验、动作
 * 执行或数据库写入逻辑，后续替换 SQLite 实现也不需要改前端契约。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel 只转发到注入的取消端口。当前调度器没有取消状态迁移，未注入端口时必须
 * fail-fast 返回能力缺口；桥接层不能通过另一个数据库连接自行删 job 或改状态。
 */
export function Cancel(input: $models.PetSchedulerCancelRequest): $CancellablePromise<$models.PetSchedulerCancelResult> {
    return $Call.ByID(1906096135, input).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RunDue 不执行 action。scheduler 只有在 job 完成确认后才会把 action payload 放进
 * Actions；桥接层把它作为稳定 JSON 返回，后续调用方再通过 PetService.PerformAction
 * 进入属性、忙碌和睡眠规则。reminder 已由 emitter 负责投递，这里只返回投递数量。
 */
export function RunDue(input: $models.PetSchedulerRunDueInput): $CancellablePromise<$models.PetSchedulerRunDueResult> {
    return $Call.ByID(55170164, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SchedulePlan 让 scheduler 完成时间归一化和批量入队；若注入了计划记录 owner，
 * 再把同一份归一化计划写入 pet_plans。两者不是跨数据库事务，因此记录失败时尽力
 * 通过同一个取消端口回滚 job，并明确返回错误，不能把半成功状态包装成成功。
 */
export function SchedulePlan(input: $models.PetSchedulerSchedulePlanInput): $CancellablePromise<$models.PetSchedulerSchedulePlanResult> {
    return $Call.ByID(4120462475, input).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ValidatePlan 只调用共享计划校验器并返回归一化计划；它不接触数据库，也不提前
 * 生成 job，避免“预览校验”产生不可见的调度副作用。
 */
export function ValidatePlan(input: $models.PetSchedulerValidatePlanInput): $CancellablePromise<$models.PetSchedulerValidatePlanResult> {
    return $Call.ByID(3593533520, input).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PetSchedulerCancelResult.createFrom;
const $$createType1 = $models.PetSchedulerRunDueResult.createFrom;
const $$createType2 = $models.PetSchedulerSchedulePlanResult.createFrom;
const $$createType3 = $models.PetSchedulerValidatePlanResult.createFrom;
