// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetService 持有宠物业务协调状态，不持有任何数据库对象。
 * 同一个服务实例内的所有读改写操作共用一把锁，保证动作和经验入账不会基于
 * 过期快照互相覆盖；跨进程并发仍需要 DAO 在实现层提供事务或串行化保证。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddExperience 把一次模型用量作为一个不可拆分的业务操作入账：总经验、总
 * token、日志、首次经验换币和宠物完整快照必须基于同一份最新快照计算。
 */
export function AddExperience(entry: $models.PetExpLogEntry): $CancellablePromise<$models.PetExperience> {
    return $Call.ByID(863661776, entry).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddExperienceFromRequestLog 接收目标项目已有 request_log 事实源。
 * ReqeustLog.ID 是持久化请求的稳定身份，因此不能用当前时间或随机数替代幂等键。
 */
export function AddExperienceFromRequestLog(logEntry: $models.ReqeustLog): $CancellablePromise<$models.PetExperience> {
    return $Call.ByID(2244465917, logEntry).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddExperienceFromUsage 将 canonical usage/pricing 转换为宠物经验日志。
 * 经验账本的唯一写入口仍是 AddExperience，因此重复事件继续复用已有的日志 ID 幂等保护。
 */
export function AddExperienceFromUsage(event: $models.PetUsageEvent): $CancellablePromise<$models.PetExperience> {
    return $Call.ByID(2448279303, event).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Bathe(): $CancellablePromise<$models.PetActionResult> {
    return $Call.ByID(566988711).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClaimDailyBonus 返回本次实际领取的金币；同一天重复调用返回 0 且不写库。
 */
export function ClaimDailyBonus(...now: number[]): $CancellablePromise<number> {
    return $Call.ByID(3341105699, now);
}

/**
 * ClaimDailyBonusForPet 是按 petId 分区的 Wails 入口。原有 ClaimDailyBonus
 * 保留给内部/兼容调用，桌宠窗口不能用无 petId 的方法避免串宠物。
 */
export function ClaimDailyBonusForPet(petID: string, now: number): $CancellablePromise<$models.PetDailyBonusResult> {
    return $Call.ByID(3462628227, petID, now).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Feed(): $CancellablePromise<$models.PetActionResult> {
    return $Call.ByID(776496909).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAgentConfig(): $CancellablePromise<$models.PetAgentConfig> {
    return $Call.ByID(3861650674).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetCareConfig(): $CancellablePromise<$models.PetCareConfig> {
    return $Call.ByID(3318750032).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetDreamConfig(): $CancellablePromise<$models.PetDreamConfig> {
    return $Call.ByID(3723044128).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetExperience 返回当前经验总账，供 Wails 设置页或等级展示直接读取。
 */
export function GetExperience(): $CancellablePromise<$models.PetExperience> {
    return $Call.ByID(2345633303).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSnapshot 返回指定宠物的前端快照。petID 必须由调用方明确提供，不能让空 ID
 * 静默回退到 default，否则多宠物场景会把设置写入错误的持久化分区。
 */
export function GetSnapshot(petID: string): $CancellablePromise<$models.PetSnapshot> {
    return $Call.ByID(2187768599, petID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetState 返回当前已经应用默认值和异常值归一化的宠物状态。
 */
export function GetState(): $CancellablePromise<$models.PetState> {
    return $Call.ByID(634081888).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetWindowConfig(): $CancellablePromise<$models.PetWindowConfig> {
    return $Call.ByID(3823832765).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListExpLog 是仓库分页能力的 Wails 友好入口。分页参数在服务层做最小兜底，
 * 具体上限和索引策略仍由 DAO 负责，避免服务层复制数据库细节。
 */
export function ListExpLog(page: number, pageSize: number): $CancellablePromise<$models.PetExpLogPage> {
    return $Call.ByID(507693454, page, pageSize).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListExperienceLog(page: number, pageSize: number): $CancellablePromise<$models.PetExpLogPage> {
    return $Call.ByID(3055965793, page, pageSize).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Load 读取并补齐完整宠物快照。默认值只在服务内补齐，不在一次只读请求中
 * 隐式写库，避免初始化失败被误报成读取失败；后续成功动作会把完整快照落盘。
 */
export function Load(): $CancellablePromise<$models.PetMigrationSnapshot> {
    return $Call.ByID(3388464177).then(($result: any) => {
        return $$createType10($result);
    });
}

export function LoadAgentConfig(): $CancellablePromise<$models.PetAgentConfig> {
    return $Call.ByID(3630994244).then(($result: any) => {
        return $$createType3($result);
    });
}

export function LoadCareConfig(): $CancellablePromise<$models.PetCareConfig> {
    return $Call.ByID(566123950).then(($result: any) => {
        return $$createType4($result);
    });
}

export function LoadDreamConfig(): $CancellablePromise<$models.PetDreamConfig> {
    return $Call.ByID(903792086).then(($result: any) => {
        return $$createType5($result);
    });
}

export function LoadWindowConfig(): $CancellablePromise<$models.PetWindowConfig> {
    return $Call.ByID(2407422131).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * MarkMilestoneForPet 只允许里程碑单调前进；较旧的客户端事件不会把已庆祝天数回退。
 */
export function MarkMilestoneForPet(petID: string, days: number): $CancellablePromise<$models.PetSnapshot> {
    return $Call.ByID(2338401890, petID, days).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PerformAction 把前端动作名映射到 PetService 的业务入口。
 * 规则层返回的 OK=false 是正常业务结果，必须原样返回；只有参数、读取或持久化
 * 失败才通过 error 返回，避免 Vue 把“宠物太饱”误报成 runtime 异常。
 */
export function PerformAction(petID: string, action: $models.PetAction): $CancellablePromise<$models.PetActionResult> {
    return $Call.ByID(3981067736, petID, action).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Petted 是 Wails 暴露的固定签名入口；petId 必须显式传入，避免 runtime 把
 * 前端动作误写到 default 分区。规则动作本身仍由内部 petted helper 执行。
 */
export function Petted(petID: string): $CancellablePromise<void> {
    return $Call.ByID(648818823, petID);
}

export function Play(): $CancellablePromise<$models.PetActionResult> {
    return $Call.ByID(3426357131).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RecordProactive 记录一次计入每日配额的主动搭话。计数必须由后端持久化，
 * 否则桌宠窗口重启或多窗口同时运行会绕过频率限制。
 */
export function RecordProactive(petID: string, now: number): $CancellablePromise<$models.PetSnapshot> {
    return $Call.ByID(1209968577, petID, now).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ResolveAwayTask 只在任务已完成时发放一次奖励。第一次成功后 state.AwayTask
 * 被规则层清空，重复调用自然返回 nil，避免重复加钱或重复增加成长值。
 */
export function ResolveAwayTask(...now: number[]): $CancellablePromise<$models.PetAwayReward | null> {
    return $Call.ByID(2945964924, now).then(($result: any) => {
        return $$createType12($result);
    });
}

export function SaveAgentConfig(config: $models.PetAgentConfig): $CancellablePromise<void> {
    return $Call.ByID(2936260499, config);
}

export function SaveCareConfig(config: $models.PetCareConfig): $CancellablePromise<void> {
    return $Call.ByID(976651331, config);
}

export function SaveDreamConfig(config: $models.PetDreamConfig): $CancellablePromise<void> {
    return $Call.ByID(1892388041, config);
}

/**
 * SaveSettings 合并指定宠物的设置并返回保存后的完整快照。配置里的非空 petId
 * 必须与路由 petID 一致；只把 petID 强制改写成目标值会掩盖前端串宠物的 bug。
 */
export function SaveSettings(petID: string, settings: $models.PetSettingsInput): $CancellablePromise<$models.PetSnapshot> {
    return $Call.ByID(2891343581, petID, settings).then(($result: any) => {
        return $$createType6($result);
    });
}

export function SaveWindowConfig(config: $models.PetWindowConfig): $CancellablePromise<void> {
    return $Call.ByID(3336139130, config);
}

export function Soak(): $CancellablePromise<$models.PetActionResult> {
    return $Call.ByID(2735498387).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartStudy(...now: number[]): $CancellablePromise<$models.PetActionResult> {
    return $Call.ByID(3034639392, now).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartWork(...now: number[]): $CancellablePromise<$models.PetActionResult> {
    return $Call.ByID(3652883170, now).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Tick 推进宠物时间状态。now 可选，主要用于测试和恢复离线时间；未传或异常
 * 时间会回退到当前毫秒时间，具体衰减和睡眠边界仍由规则层统一计算。
 */
export function Tick(...now: number[]): $CancellablePromise<$models.PetState> {
    return $Call.ByID(461800748, now).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ToggleSleep 返回切换后的状态。规则层对 away task 的切换请求是无操作，服务层
 * 仍会把 Tick 产生的时间结算保存下来，但不会凭空改变 away task。
 */
export function ToggleSleep(...now: number[]): $CancellablePromise<$models.PetState> {
    return $Call.ByID(4161072560, now).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * UpdateName 是宠物名称的唯一写入口。名称属于 PetState，而不是设置配置；
 * 单独读取并保存最新快照，避免设置页只提交配置时把桌宠窗口刚产生的状态覆盖掉。
 */
export function UpdateName(petID: string, name: string): $CancellablePromise<$models.PetSnapshot> {
    return $Call.ByID(2676971095, petID, name).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PetExperience.createFrom;
const $$createType1 = $models.PetActionResult.createFrom;
const $$createType2 = $models.PetDailyBonusResult.createFrom;
const $$createType3 = $models.PetAgentConfig.createFrom;
const $$createType4 = $models.PetCareConfig.createFrom;
const $$createType5 = $models.PetDreamConfig.createFrom;
const $$createType6 = $models.PetSnapshot.createFrom;
const $$createType7 = $models.PetState.createFrom;
const $$createType8 = $models.PetWindowConfig.createFrom;
const $$createType9 = $models.PetExpLogPage.createFrom;
const $$createType10 = $models.PetMigrationSnapshot.createFrom;
const $$createType11 = $models.PetAwayReward.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
