// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetWindowAPI 只把原生窗口状态机暴露给 Wails，不参与宠物设置持久化。
 * 配置落盘由 PetService 负责，调用方在确认保存成功后再调用这里的生命周期方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(4235172168);
}

export function Focus(): $CancellablePromise<void> {
    return $Call.ByID(2356266780);
}

/**
 * IdleSeconds 返回系统级最后输入到当前时刻的秒数。
 * 该能力不属于窗口 driver：Windows 需要直接读取 user32，全局窗口状态机不应被平台 API 污染。
 */
export function IdleSeconds(): $CancellablePromise<number> {
    return $Call.ByID(44600571);
}

export function Move(x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(1321218785, x, y);
}

export function Open(): $CancellablePromise<void> {
    return $Call.ByID(219091156);
}

export function Resize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(3844190092, width, height);
}

export function SetAlwaysOnTop(alwaysOnTop: boolean): $CancellablePromise<void> {
    return $Call.ByID(4238057735, alwaysOnTop);
}

/**
 * 以下方法只负责 Wails 参数适配和统一 nil 兜底，具体窗口行为仍由 PetWindow 状态机决定。
 */
export function SetMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3798240959, mode);
}

export function State(): $CancellablePromise<$models.PetWindowState> {
    return $Call.ByID(3374424649).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Toggle(): $CancellablePromise<void> {
    return $Call.ByID(677412704);
}

// Private type creation functions
const $$createType0 = $models.PetWindowState.createFrom;
