// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearProjectCodexProvider(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(1724402302, projectPath);
}

export function DeleteProject(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(1017476374, projectPath);
}

export function DeleteSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2666625055, sessionID);
}

export function ForkSessionConversation(sessionID: string, messageIDs: string[]): $CancellablePromise<$models.SessionSummary> {
    return $Call.ByID(2531626241, sessionID, messageIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetCodexRuntimeStatusSnapshot(): $CancellablePromise<$models.CodexRuntimeStatusSnapshot> {
    return $Call.ByID(2587763889).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSessionConversationDetail(sessionID: string): $CancellablePromise<$models.SessionConversationDetail> {
    return $Call.ByID(2599842864, sessionID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetSnapshot(): $CancellablePromise<$models.ProjectManagerSnapshot> {
    return $Call.ByID(1402859362).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListProjectSessions(projectPath: string): $CancellablePromise<$models.SessionSummary[]> {
    return $Call.ByID(3482480734, projectPath).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListProjects(): $CancellablePromise<$models.ProjectSummary[]> {
    return $Call.ByID(2806071092).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListRecentSessions(): $CancellablePromise<$models.SessionSummary[]> {
    return $Call.ByID(1055571516).then(($result: any) => {
        return $$createType4($result);
    });
}

export function OpenProjectFolder(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(962621967, projectPath);
}

export function OpenProjectTerminal(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(3615257703, projectPath);
}

export function OpenSessionTerminal(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1009513054, sessionID);
}

export function OpenSessionTerminalWithSession(session: $models.SessionSummary): $CancellablePromise<void> {
    return $Call.ByID(2081160126, session);
}

export function PruneSessionConversation(sessionID: string, messageIDs: string[]): $CancellablePromise<$models.SessionConversationDetail> {
    return $Call.ByID(1933876465, sessionID, messageIDs).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RefreshProjectIndex(): $CancellablePromise<$models.ProjectManagerSnapshot> {
    return $Call.ByID(4024905526).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RenameProject(projectPath: string, displayName: string): $CancellablePromise<void> {
    return $Call.ByID(690378353, projectPath, displayName);
}

export function RenameSession(sessionID: string, displayName: string): $CancellablePromise<void> {
    return $Call.ByID(1130005944, sessionID, displayName);
}

export function RunProjectAICommit(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(1250976875, projectPath);
}

export function RunProjectCommand(projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(757489369, projectPath);
}

export function SaveProjectRunCommand(projectPath: string, command: string): $CancellablePromise<void> {
    return $Call.ByID(488284630, projectPath, command);
}

export function SearchProjectSessionConversations(projectPath: string, query: string): $CancellablePromise<$models.ProjectSessionSearchResult[]> {
    return $Call.ByID(2204346111, projectPath, query).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2784582113, app);
}

export function SetProjectCodexProvider(projectPath: string, providerID: number): $CancellablePromise<void> {
    return $Call.ByID(1805942307, projectPath, providerID);
}

export function SetProjectCodexProviderRouting(projectPath: string, providerID: number, autoFallback: boolean): $CancellablePromise<void> {
    return $Call.ByID(971476843, projectPath, providerID, autoFallback);
}

export function StartCodexStatusMonitor(): $CancellablePromise<void> {
    return $Call.ByID(662751623);
}

export function StopCodexStatusMonitor(): $CancellablePromise<void> {
    return $Call.ByID(1325852391);
}

// Private type creation functions
const $$createType0 = $models.SessionSummary.createFrom;
const $$createType1 = $models.CodexRuntimeStatusSnapshot.createFrom;
const $$createType2 = $models.SessionConversationDetail.createFrom;
const $$createType3 = $models.ProjectManagerSnapshot.createFrom;
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $models.ProjectSummary.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.ProjectSessionSearchResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
