// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RadarService 负责读取公开雷达数据，并在后端完成聚合。
 * 原站接口未返回 CORS 许可头，不能让 Wails WebView 直接请求，否则会被浏览器拦截。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSnapshot 拉取一次原站数据并返回已聚合的页面快照。
 */
export function GetSnapshot(): $CancellablePromise<$models.RadarSnapshot | null> {
    return $Call.ByID(4141856308).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RadarSnapshot.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
